name: Release

on:
  release:
    types: [published]

jobs:
  release:
    uses: eddiecarpenter/gh-agentic/.github/workflows/release.yml@v2.8.9
    secrets: inherit
    permissions:
      contents: write
